version: '3.4'

services:
  l4d4react:
    image: l4d4react
    container_name: l4d4_react
    restart: always
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    expose:
      - 3000