version: '3.4'

services:
  l4d4react:
    image: l4d4react
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
